'use strict';
const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name="studio-token"]').content;
const fields=['project','shot','purpose','subject','style','audience','prompt','price'];
let selected=null,lastJob='',objectUrl=null,snapshot=null,busy=false,pending=false,selectVersion=0;
let historySignature='';
let firstRefresh=true;
const labels={succeeded:'已生成',failed:'失败',unknown:'等待查询',draft:'未提交'};
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function data(){return {project:$('project').value.trim(),shot_no:Number($('shot').value),purpose:$('purpose').value,subject:$('subject').value,style:$('style').value,audience:$('audience').value,prompt:$('prompt').value,price:$('price').value,request_id:selected?.request_id,confirmed:true};}
function saveDraft(){try{localStorage.setItem('kantoku-draft',JSON.stringify(Object.fromEntries(fields.map(k=>[k,$(k).value]))));}catch{}}
try{const draft=JSON.parse(localStorage.getItem('kantoku-draft')||'{}');for(const key of fields)if(typeof draft[key]==='string')$(key).value=draft[key];}catch{}
fields.forEach(key=>$(key).addEventListener('input',saveDraft));
async function request(path,body){const response=await fetch(path,{headers:{'X-Studio-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result;}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(b=>{if(!b.closest('dialog')&&!b.classList.contains('nav'))b.disabled=value;});}
async function run(action,payload=data()){if(busy||pending)return;pending=true;setBusy(true);notice('正在处理，请稍候。原任务记录会保留。');try{await request('/api/'+action,payload);await refresh();}catch(e){notice(e.message,true);setBusy(false);}finally{pending=false;}}
function confirmAction(title,message,withPrice=false){return new Promise(resolve=>{$('dialog-title').textContent=title;$('dialog-message').textContent=message;$('dialog-field').hidden=!withPrice;$('dialog-confirm').textContent=withPrice?'确认实扣':'确认继续';$('bill-price').value='';$('dialog').returnValue='';$('dialog').showModal();$('dialog').addEventListener('close',()=>resolve($('dialog').returnValue==='confirm'),{once:true});});}
function taskButton(task){const button=document.createElement('button');button.textContent=task.project+' / '+task.shot_no;const detail=document.createElement('span');detail.textContent=(labels[task.status]||task.status)+' · '+task.request_id.slice(-8);button.append(detail);button.classList.toggle('selected',selected?.request_id===task.request_id);button.onclick=()=>{selectTask(task);view('create');};button.disabled=busy;return button;}
function renderHistory(tasks){const signature=JSON.stringify([tasks,selected?.request_id]);if(signature===historySignature)return;historySignature=signature;$('history').replaceChildren(...tasks.map(taskButton));$('archive').replaceChildren(...tasks.map(taskButton));$('count').textContent=tasks.length+' RECORDS';if(!tasks.length){const p=document.createElement('p');p.textContent='还没有生成记录。你的第一张画面将保存在这里。';$('history').append(p);}}
async function selectTask(task){if(busy)return;const version=++selectVersion;selected=task;$('project').value=task.project;$('shot').value=task.shot_no;$('prompt').value=task.prompt;saveDraft();$('task-caption').textContent=task.project+' / 镜 '+task.shot_no;$('task-status').textContent=labels[task.status]||task.status;$('review-text').textContent='当前画面尚未在本次会话预筛。请先人工检查表情、接触关系、材质与场景逻辑。';$('empty').hidden=task.has_image;$('artwork').hidden=true;renderHistory(snapshot.tasks);if(objectUrl){URL.revokeObjectURL(objectUrl);objectUrl=null;}if(task.has_image){try{const response=await fetch('/media/'+task.request_id,{headers:{'X-Studio-Token':token}});if(!response.ok)throw Error('图片读取失败');const blob=await response.blob();if(version!==selectVersion)return;objectUrl=URL.createObjectURL(blob);$('artwork').src=objectUrl;$('artwork').hidden=false;}catch(e){notice(e.message,true);}}notice(task.error||'已选择历史画面。查询和继续任务会沿用原任务 ID。');}
async function refresh(){try{snapshot=await request('/api/state');$('limit').textContent='¥'+snapshot.config.limit;$('image-size').textContent=snapshot.config.size;const job=snapshot.job;if(firstRefresh){lastJob=job.state==='running'?'':job.id||'';firstRefresh=false;}setBusy(job.state==='running');renderHistory(snapshot.tasks);if(selected){const fresh=snapshot.tasks.find(t=>t.request_id===selected.request_id);if(fresh)selected=fresh;}if(job.id&&job.id!==lastJob&&job.state!=='running'){lastJob=job.id;if(job.state==='error'){notice(job.error,true);}else{const r=job.result||{};if(r.prompt){$('prompt').value=r.prompt;saveDraft();notice('提示词已更新，请检查后再生成。');}if(r.request_id){const task=snapshot.tasks.find(t=>t.request_id===r.request_id);if(task)await selectTask(task);}if(r.qc){$('review-text').textContent=r.qc.reason+'\n\n模型置信度：'+Math.round(r.qc.confidence*100)+'%（不是质量分）';notice('预筛完成，请结合实际画面判断。');}if(r.message)notice(r.message);if(job.action==='budget')notice('已结算 '+r.settled_fen+' 分 / 预占 '+r.held_fen+' 分 / 剩余 '+r.available_fen+' 分');}}}catch(e){notice('连接暂不可用：'+e.message+'。请确认启动窗口仍在运行。',true);}}
$('compose').onclick=()=>run('compose');
$('refine').onclick=async()=>{if(!$('prompt').value.trim()){notice('请先整理提示词或填入设计需求。',true);return;}if(await confirmAction('优化画面设计','将当前提示词发送给已配置的文本模型。\n文本模型可能收费，费用不在生图台账中。'))run('refine');};
$('generate').onclick=async()=>{const d=data();if(!d.project||!d.prompt.trim()||!Number.isInteger(d.shot_no)||d.shot_no<1||!(Number(d.price)>0)){notice('请填写作品名、正整数画面编号、提示词和核实的费用上界。',true);return;}if(await confirmAction('生成一张画面',`作品：${d.project} / 画面 ${d.shot_no}\n本次预占上界：¥${d.price}\n将发送最终提示词给生图供应商。\n这是一个新候选；查询已有任务请使用“查询进度”。`))run('generate',d);};
$('recover').onclick=()=>{if(!selected){notice('请先选择历史任务。',true);return;}run('recover');};
$('resume').onclick=async()=>{if(!selected){notice('请先选择历史任务。',true);return;}if(await confirmAction('继续原任务',`沿用已保存的提示词与费用上界 ¥${(selected.estimate_fen/100).toFixed(2)}。\n未提交任务将执行一次；已提交任务不会重复提交。`))run('resume');};
$('qc').onclick=async()=>{if(!selected?.has_image){notice('请先选择一张已生成图片。',true);return;}if(await confirmAction('视觉模型预筛','将当前图片与审片要求发送给视觉模型。\n可能收费，不包含在生图台账内。结果仅为辅助意见。'))run('qc');};
$('bill').onclick=async()=>{if(!selected){notice('请先选择历史任务。',true);return;}try{const state=await request('/api/state');const task=state.tasks.find(t=>t.request_id===selected.request_id);if(await confirmAction('核对供应商账单',`当前任务：${task.request_id.slice(-8)}\n已记录实扣：${task.actual_fen===null?'待对账':task.actual_fen+' 分'}\n仅填写平台已确认的最终费用；查看项目预算请点返回。`,true))run('settle',{...data(),price:$('bill-price').value});else run('budget');}catch(e){notice(e.message,true);}};
$('download').onclick=()=>{if(!objectUrl){notice('请先选择一张可用图片。',true);return;}const a=document.createElement('a');a.href=objectUrl;a.download=selected.request_id+'.png';a.click();};
$('settings').onclick=async()=>{if(!snapshot)return;const c=snapshot.config;await confirmAction('当前模型配置',`生图：${c.image}\n文本：${c.chat}\n视觉：${c.vision}\n输出尺寸：${c.size}\n配置从本地读取，密钥不发送到浏览器。`);};
function view(name){$('create-view').hidden=name!=='create';$('archive-view').hidden=name!=='archive';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{$('style').value=b.dataset.style;document.querySelectorAll('[data-style]').forEach(x=>x.classList.toggle('selected',x===b));saveDraft();});
async function loop(){await refresh();setTimeout(loop,1800);}loop();
